### ISSUE TITLE
Update Modules demo app

### ISSUE THREAD

**Issue by yallen011** [rangle/augury-examples#83]
# Tasks
- [ ] Update Modules demo app to Angular v8. 
- [ ] Change the Modules README.md to display the correct name in the title.

**Comment by yallen011** [comment]
@sumitarora Currently I see 2 app folders in this project. Is there a reason for this?

**Comment by feeloor** [comment]
> @sumitarora Currently I see 2 app folders in this project. Is there a reason for this?
@yallen011 The app-folder in the root is the compiled code.
